-> cve1789_server
ACCEPT..
SSL_accept:before/accept initialization
SSL_accept:SSLv3 read client hello A
SSL_accept:SSLv3 write server hello A
SSL_accept:SSLv3 write certificate A
SSL_accept:SSLv3 write certificate request A
SSL_accept:SSLv3 flush data
verifyClientCertificate()::error = 0 depth = 1:ok
Cert subject = /C=in/ST=ka/L=ba/O=neo/OU=neo/CN=neo/emailAddress=ja&com
Cert issuer = /C=in/ST=ka/L=ba/O=neo/OU=neo/CN=neo/emailAddress=ja&com

func: internal_verify line: 737	X509_verify_err: Collected return value is less than 0, Action: Ignore 
verifyClientCertificate()::error = 7 depth = 0:certificate signature failure
Cert subject = /C=in/ST=ka/L=ba/O=neo/OU=neo/CN=neo/emailAddress=ja.com
Cert issuer = /C=in/ST=ka/L=ba/O=neo/OU=neo/CN=neo/emailAddress=ja&com

 [X509_cmp_time]952: OUT OF BOUND READ ACCESS DETECTED!
SSL3 alert write:fatal:handshake failure
SSL_accept:error in SSLv3 read client certificate B
SSL_accept:error in SSLv3 read client certificate B
SSL_accept returned error, error:7F06D064:lib(127):func(109):CCI call fails, check return code
Connection terminating..
value = 0 = 0x0
-> 

